package edu.xtu.androidbase.weaher.ui.weather.domain;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "T_Province".
*/
public class ProvinceDao extends AbstractDao<Province, String> {

    public static final String TABLENAME = "T_Province";

    /**
     * Properties of entity Province.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ProName = new Property(0, String.class, "proName", true, "ProName");
        public final static Property ProSort = new Property(1, String.class, "proSort", false, "ProSort");
        public final static Property ProRemark = new Property(2, String.class, "proRemark", false, "ProRemark");
    }


    public ProvinceDao(DaoConfig config) {
        super(config);
    }
    
    public ProvinceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Province entity) {
        stmt.clearBindings();
 
        String proName = entity.getProName();
        if (proName != null) {
            stmt.bindString(1, proName);
        }
 
        String proSort = entity.getProSort();
        if (proSort != null) {
            stmt.bindString(2, proSort);
        }
 
        String proRemark = entity.getProRemark();
        if (proRemark != null) {
            stmt.bindString(3, proRemark);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Province entity) {
        stmt.clearBindings();
 
        String proName = entity.getProName();
        if (proName != null) {
            stmt.bindString(1, proName);
        }
 
        String proSort = entity.getProSort();
        if (proSort != null) {
            stmt.bindString(2, proSort);
        }
 
        String proRemark = entity.getProRemark();
        if (proRemark != null) {
            stmt.bindString(3, proRemark);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Province readEntity(Cursor cursor, int offset) {
        Province entity = new Province( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // proName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // proSort
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // proRemark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Province entity, int offset) {
        entity.setProName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setProSort(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProRemark(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Province entity, long rowId) {
        return entity.getProName();
    }
    
    @Override
    public String getKey(Province entity) {
        if(entity != null) {
            return entity.getProName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Province entity) {
        return entity.getProName() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
