package edu.xtu.androidbase.weaher.ui.weather.domain;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SELECT_CITY".
*/
public class SelectCityDao extends AbstractDao<SelectCity, Long> {

    public static final String TABLENAME = "SELECT_CITY";

    /**
     * Properties of entity SelectCity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property CityId = new Property(1, long.class, "cityId", false, "CITY_ID");
        public final static Property CityName = new Property(2, String.class, "cityName", false, "CITY_NAME");
    }


    public SelectCityDao(DaoConfig config) {
        super(config);
    }
    
    public SelectCityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELECT_CITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"CITY_ID\" INTEGER NOT NULL ," + // 1: cityId
                "\"CITY_NAME\" TEXT);"); // 2: cityName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELECT_CITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelectCity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getCityId());
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(3, cityName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelectCity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getCityId());
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(3, cityName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public SelectCity readEntity(Cursor cursor, int offset) {
        SelectCity entity = new SelectCity( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // cityId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // cityName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelectCity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setCityId(cursor.getLong(offset + 1));
        entity.setCityName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelectCity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelectCity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SelectCity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
